spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:proddb}
    username: ${DATABASE_USERNAME:prod}
    password: ${DATABASE_PASSWORD:prod}
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  
  h2:
    console:
      enabled: false

logging:
  level:
    com.example.template: INFO
    org.springframework: WARN
    org.hibernate.SQL: WARN
  file:
    name: /var/log/spring-boot-template/application.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never