name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  JAVA_VERSION: "17"
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: mvn clean test

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit

      - name: Code Coverage
        run: mvn jacoco:report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        if: success()
        with:
          file: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: false

      - name: Publish Test Results to CloudBees Platform
        uses: cloudbees-io-gha/publish-test-results@v2
        if: success() || failure()
        with:
          test-type: junit
          results-path: target/surefire-reports

  lint:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: maven

      - name: Run Checkstyle
        run: mvn checkstyle:check
        continue-on-error: true

      - name: Run SpotBugs
        run: mvn spotbugs:check
        continue-on-error: true

  build-and-deploy:
    name: Build and Deploy to Nexus
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: maven

      - name: Configure Maven settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
              "id": "nexus-releases",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            },
            {
              "id": "nexus-snapshots",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]

      - name: Set version from Git
        id: version
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          SHORT_SHA=$(git rev-parse --short HEAD)
          NEW_VERSION="1.0.0-${COMMIT_COUNT}-${SHORT_SHA}"
          echo "Setting version to: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          mvn versions:set -DnewVersion="$NEW_VERSION"

      - name: Build and Deploy to Nexus
        run: mvn clean deploy -DskipTests -Dnexus.url="${NEXUS_URL}"
        env:
          NEXUS_URL: ${{ secrets.NEXUS_URL }}

      - name: Register Build Artifacts in CloudBees Platform
        id: register-artifact
        uses: cloudbees-io-gha/register-build-artifact@v3
        with:
          name: ${{ github.repository }}
          url: ${{ secrets.NEXUS_URL }}/repository/maven-releases/${{ github.repository }}
          version: ${{ steps.version.outputs.version }}
          type: Maven

      - name: Add Labels to Artifact
        uses: cloudbees-io-gha/label-artifact-version@v1
        with:
          artifact-id: ${{ steps.register-artifact.outputs.cbp_artifact_id }}
          labels: "main,maven,nexus"

      - name: Publish Build Evidence
        uses: cloudbees-io-gha/publish-evidence-item@v2
        with:
          content: |-
            # Build Evidence Report

            ## Artifact Details
            - **Repository**: ${{ github.repository }}
            - **Version**: ${{ steps.version.outputs.version }}
            - **Artifact ID**: ${{ steps.register-artifact.outputs.cbp_artifact_id }}
            - **Type**: Maven

            ## Deployment
            - **Target**: Nexus Repository
            - **URL**: ${{ secrets.NEXUS_URL }}
            - **Labels**: main, maven, nexus

            ## Workflow Summary
            - **Branch**: ${{ github.ref_name }}
            - **Commit**: ${{ github.sha }}
            - **Run**: ${{ github.run_number }}
            - **Triggered by**: ${{ github.event_name }}
